system.py: avoid filenames in backup dialog
Unexpected filename encodings can cause unhandled exceptions in
Python, Kodi and/or the addon. Avoid the issue for now by not
displaying, and thereby converting, the filename.

Example:

ERROR <general>: SETTINGS: system.tar_add_folder # UnicodeEncodeError('utf-8', 'SETTINGS: tar_add_folder # Adding to backup: /storage/.kodi/addons/service.nextpvr/nextpvr-bin/data/tuning/DVB-T/France - Bess\udc8ages.ini', 126, 127, 'surrogates not allowed')
ERROR <general>: Traceback (most recent call last):
    File "/usr/share/kodi/addons/service.libreelec.settings/resources/lib/log.py", line 45, in _log_function_2
    File "/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/system.py", line 578, in tar_add_folder
    File "/usr/share/kodi/addons/service.libreelec.settings/resources/lib/log.py", line 32, in log
    File "/usr/share/kodi/addons/service.libreelec.settings/resources/lib/log.py", line 25, in _log
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc8a' in position 126: surrogates not allowed

Signed-off-by: Ian Leonard <antonlacon@gmail.com>